packages:
  - docs
  - example
  - playground
onlyBuiltDependencies:
  - better-sqlite3
  - maplibre-gl
  - puppeteer
  - sharp
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - onnxruntime-node
  - protobufjs
  - vue-demi
